//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        public static string Frg_AdvancedSettings {
            get {
                return ResourceManager.GetString("Frg_AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Frg_Exit {
            get {
                return ResourceManager.GetString("Frg_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Frg_Height {
            get {
                return ResourceManager.GetString("Frg_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name.
        /// </summary>
        public static string Frg_ProcessName {
            get {
                return ResourceManager.GetString("Frg_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore windows.
        /// </summary>
        public static string Frg_RestoreWindows {
            get {
                return ResourceManager.GetString("Frg_RestoreWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Frg_Save {
            get {
                return ResourceManager.GetString("Frg_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store active window.
        /// </summary>
        public static string Frg_StoreActiveWindow {
            get {
                return ResourceManager.GetString("Frg_StoreActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store all windows.
        /// </summary>
        public static string Frg_StoreAllWindows {
            get {
                return ResourceManager.GetString("Frg_StoreAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Frg_Title {
            get {
                return ResourceManager.GetString("Frg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Frg_Width {
            get {
                return ResourceManager.GetString("Frg_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active window position has been stored..
        /// </summary>
        public static string Msg_ActiveWindowStored {
            get {
                return ResourceManager.GetString("Msg_ActiveWindowStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All window positions have been stored..
        /// </summary>
        public static string Msg_AllWindowsStored {
            get {
                return ResourceManager.GetString("Msg_AllWindowsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been saved..
        /// </summary>
        public static string Msg_SettingsSaved {
            get {
                return ResourceManager.GetString("Msg_SettingsSaved", resourceCulture);
            }
        }
    }
}
